### ISSUE TITLE
No way to set Property Access

### ISSUE THREAD

**Issue by csnewman** [tmds/Tmds.DBus#48]
There is no current way to specify the PropertyAccess of a property, currently it is set to ReadWrite always.
It would be helpful if an attribute could be added that allows the setting of this.

**Comment by tmds** [comment]
> There is no current way to specify the PropertyAccess of a property, currently it is set to ReadWrite always.

Yes, it is hard coded to `ReadWrite`:
https://github.com/tmds/Tmds.DBus/blob/eb2899f449681c3ed238f0c9000e8d16614027a5/src/Tmds.DBus/CodeGen/TypeDescription.cs#L355

> It would be helpful if an attribute could be added that allows the setting of this.

For properties we use the fields of a class/struct that has the `Dictionary` attribute.

I'm leaning towards a `PropertyAttribute` that takes a `PropertyAccess` (this is currently an internal enum in `Tmds.DBus.CodeGen`, we can move it to `Tmds.DBus` and make it public).

If you want to implement this, I accept PRs :smiley:. Otherwise it will take some time till I look at it.

**Comment by csnewman** [comment]
Yeah, that was the implementation I was thinking of.

At the moment, in my use cases, it doesn't really matter that the introspection data is wrong as I only use the dbus internally and isn't documented for external use. Meaning it's unlikely I'll have time to implement this anytime soon either.

**Comment by csnewman** [comment]
See PR #54
